# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Shapefileloader
                                 A QGIS plugin
 This plugin loads shapefiles
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-31
        copyright            : (C) 2020 by Lenny
        email                : boblenny23@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Shapefileloader class from file Shapefileloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Shapefile_loader import Shapefileloader
    return Shapefileloader(iface)
